# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 040b4a8146453653b0e8b7561c3ad957261d383cb4aeca2850f49dc3c7476c1c52f221279445d555feba854b5463223f4bde2cdc4b95f0c59a2c98374b7bd2cc

test:
  secret_key_base: 81c01f57e69435b29e08559fe067257daa4ff9b43d78f67fd50d8f495ef746a7f01f1b42d6a04bcc5b172005f9533bef94be2ddf358bddcb2e471306cdbe789c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
